apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: petite-maison-backend-pdb
  namespace: petite-maison-epouvante
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: petite-maison-backend
