apiVersion: v1
kind: Service
metadata:
  name: petite-maison-backend
  namespace: petite-maison-epouvante
  labels:
    app: petite-maison-backend
spec:
  type: NodePort
  selector:
    app: petite-maison-backend
  ports:
    - name: http
      port: 4003
      targetPort: 4003
      nodePort: 30003
