apiVersion: v1
kind: Service
metadata:
  name: petite-maison-frontend
  namespace: petite-maison-epouvante
  labels:
    app: petite-maison-frontend
spec:
  type: NodePort
  selector:
    app: petite-maison-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
