apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petite-maison-epouvante-ingress
  namespace: petite-maison-epouvante
spec:
  ingressClassName: nginx
  rules:
    - host: petite-maison-epouvante.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: petite-maison-frontend
                port:
                  number: 80
