apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petite-maison-epouvante-ingress-tls
  namespace: petite-maison-epouvante
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - petite-maison-epouvante.local
      secretName: petite-maison-epouvante-tls
  rules:
    - host: petite-maison-epouvante.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: petite-maison-frontend
                port:
                  number: 80
