apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collector-shop-ingress-tls
  namespace: collector-shop
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - collector-shop.local
      secretName: collector-shop-tls
  rules:
    - host: collector-shop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: collector-frontend
                port:
                  number: 80
